handle missing element by not generating a hyperlink
ERROR    2012-03-24 18:13:38,681 plusfeed.py:375] coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "/dev/github.com/dabble/plusfeed/plusfeed.py", line 309, in doFeed
    desc = desc + ' <br/><br/><a href="' + post[66][0][1] + '">' + post[66][0][3] + '</a>'
TypeError: coercing to Unicode: need string or buffer, NoneType found
INFO     2012-03-24 18:13:38,695 dev_appserver.py:4247] "GET /114474252347218597235 HTTP/1.0" 500 -